Bold
safe-global/safe-android pull request #1797
Opened 2022-09-01 12:20 UTC by biafra23

Handles #1796 

Changes proposed in this pull request:
![image](https://user-images.githubusercontent.com/246473/187912273-1096bc9d-7dec-4530-aaac-7156a2a108e5.png)

@gnosis/mobile-devs

2022-09-01 12:37 UTC, elgatovital commented
@biafra23 Where is the paragraph?

2022-09-01 12:40 UTC, elgatovital requested changes

2022-09-01 12:40 UTC, elgatovital commented on app/src/main/res/values/strings.xml
> +    <string name="whatsnew_item1_description">&lt;b&gt;Gnosis Safe &lt;/b&gt; rebranded to &lt;b&gt;Safe&lt;/b&gt;. Following a successful spin-off vote from Gnosis in GIP-29, we are rebranding to Sa
I would rather work with Spannables and set ForegroundColorSpan for highlighted elements

2022-09-01 12:44 UTC, elgatovital commented
@biafra23 could you also replace `ic_app_24dp.xml` with the new logo in this pr?

2022-09-01 12:45 UTC, elgatovital commented on app/src/main/res/values/strings.xml
> +    <string name="whatsnew_item1_description">&lt;b&gt;Gnosis Safe &lt;/b&gt; rebranded to &lt;b&gt;Safe&lt;/b&gt;. Following a successful spin-off vote from Gnosis in GIP-29, we are rebranding to Sa
also highlighted elements are not bold, but have different color in design mocks

2022-09-01 14:15 UTC, biafra23 commented
> @biafra23 could you also replace ic_app_24dp.xml with the new logo in this pr?

I wanted to do that in a separate PR.

2022-09-01 15:26 UTC, biafra23 commented on app/src/main/res/drawable/ic_app_24dp.xml
> +        android:fillColor="#ffffff"/>
![image](https://user-images.githubusercontent.com/246473/187952513-8298168f-4145-4833-81a3-261dbe5197e4.png)

Looks good now

2022-09-02 09:44 UTC, elgatovital approved these changes

2022-09-02 09:45 UTC, merged